-- CreateEnum
CREATE TYPE "VolumeTrackingMuscle" AS ENUM ('CHEST', 'UPPER_CHEST', 'LOWER_CHEST', 'LATS', 'UPPER_BACK', 'LOWER_BACK', 'RHOMBOIDS', 'MID_TRAPS', 'LOWER_TRAPS', 'FRONT_DELTS', 'SIDE_DELTS', 'REAR_DELTS', 'BICEPS', 'TRICEPS_LATERAL_HEAD', 'TRICEPS_MEDIAL_HEAD', 'TRICEPS_LONG_HEAD', 'FOREARMS', 'ABS', 'OBLIQUES', 'GLUTES', 'HIP_FLEXORS', 'QUADRICEPS', 'HAMSTRINGS', 'ADDUCTORS', 'CALVES', 'TIBIALIS_ANTERIOR');

-- AlterTable
ALTER TABLE "Exercise" ADD COLUMN     "volumeContributions" JSONB;
