/*
  Warnings:

  - The values [CHEST,LATS,UPPER_BACK,LOWER_BACK,MID_TRAPS,LOWER_TRAPS,FOREARMS,GLUTES,QUADRICEPS,ADDUCTORS] on the enum `VolumeTrackingMuscle` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "VolumeTrackingMuscle_new" AS ENUM ('UPPER_CHEST', 'MIDDLE_CHEST', 'LOWER_CHEST', 'BICEPS', 'BRACHIALIS', 'BRACHIORADIALIS', 'TRICEPS_LONG_HEAD', 'TRICEPS_MEDIAL_HEAD', 'TRICEPS_LATERAL_HEAD', 'FRONT_DELTS', 'SIDE_DELTS', 'REAR_DELTS', 'WRIST_FLEXORS', 'WRIST_EXTENSORS', 'UPPER_LATS', 'MIDDLE_LATS', 'LOWER_LATS', 'TRAPEZIUS', 'RHOMBOIDS', 'ERECTOR_SPINAE', 'GLUTEUS_MAXIMUS', 'GLUTEUS_MEDIUS', 'GLUTEUS_MINIMUS', 'ADDUCTOR_MAGNUS', 'OTHER_ADDUCTORS', 'RECTUS_FEMORIS', 'VASTUS_LATERALIS', 'VASTUS_MEDIALIS', 'VASTUS_INTERMEDIUS', 'HAMSTRINGS', 'CALVES', 'TIBIALIS_ANTERIOR', 'ABS', 'OBLIQUES', 'HIP_FLEXORS', 'SERRATUS_ANTERIOR', 'PECTORALIS_MINOR', 'TERES_MAJOR', 'TERES_MINOR', 'INFRASPINATUS', 'SUPRASPINATUS', 'SUBSCAPULARIS');
ALTER TYPE "VolumeTrackingMuscle" RENAME TO "VolumeTrackingMuscle_old";
ALTER TYPE "VolumeTrackingMuscle_new" RENAME TO "VolumeTrackingMuscle";
DROP TYPE "VolumeTrackingMuscle_old";
COMMIT;
